environment: production
title: Hexancore
email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  Hexancore is advanced framework based on NestJs to build hexagonal architecture designed apps
baseurl: "/hexancore"
url: "https://hexancore.github.io"
github_username:  haxancore

remote_theme: just-the-docs/just-the-docs

plugins:
  - jekyll-feed

include: ['_pages']

footer_content: "Copyright &copy; 2021-2022 Andrzej Wasiak<Mararok>"